name: Build Debian RootFS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install debootstrap
        run: sudo apt-get update && sudo apt-get install -y debootstrap

      - name: Create Debian rootfs
        run: |
          sudo debootstrap --arch=amd64 --include=vim,nano,htop,wget,curl,neofetch stable rootfs/debian-rootfs
          
      - name: Pack rootfs
        run: |
          cd rootfs/; tar czvf debian-rootfs.tar --exclude=var/cache/apt/archives/* --exclude=var/lib/apt/lists/* --exclude=tmp/* --exclude=var/log/* debian-rootfs || true
          rm -rf rootfs/debian-rootfs

      - name: Upload rootfs to repository
        run: |
          git lfs track "*.tar"
          git add rootfs/debian-rootfs.tar
          git commit -m "Uploaded rootfs image"
          git push origin main