name: Build Debian RootFS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install debootstrap
        run: sudo apt-get update && sudo apt-get install -y debootstrap

      - name: Create Debian rootfs
        run: |
          mkdir -p rootfs/
          sudo debootstrap --arch=amd64 --include=vim,nano,htop,wget,curl,neofetch stable rootfs/debian-rootfs
          
      - name: Pack rootfs
        run: |
          cd rootfs/; tar czvf debian-rootfs.tar --exclude=var/cache/apt/archives/* --exclude=var/lib/apt/lists/* --exclude=tmp/* --exclude=var/log/* debian-rootfs || true
          rm -rf rootfs/debian-rootfs

      - name: Commit rootfs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git lfs track "*.tar"
          git add rootfs/debian-rootfs.tar
          git commit -m "Uploaded rootfs image"
      
      - name: Upload rootfs to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}